### ISSUE TITLE
Extension does not allow app to run

### ISSUE THREAD

**Issue by Cyberuben** [nickchops/s3eAndroidFullscreen#2]
When including this extension in my Marmalade app, my app crashes on startup. I see about a second of Marmalade's debug view, then as I expect the Marmalade logo, the app shuts down without a crashlog. Is there any specific reason why this should crash my application?

My phone is a LG Nexus 5 running Android 4.4.4 (build KTU84P)

**Comment by Cyberuben** [comment]
I still have this issue. Any chance you could look into this?

**Comment by nickchops** [comment]
Ill take a look this eve. Ive got an nexus 4 on 4.4.4 to test on. Did you update the android.jar in Marmalade to lvl19 or newer? Not sure if that would be a compile or runtime crash off hand.

Typically crash-on-startup is related to missing or incorrect extension libraries (jar in Android's case).

Are you using C++ or Lua?

**Comment by Cyberuben** [comment]
I have done this, yes, but it didn't seem to work.

**Comment by Cyberuben** [comment]
After attaching logcat I've come to the conclusion it has to do with my license. Apparently a free license is not allowed to use 3rd party extensions. I thought I had a Student license. Sorry for wasting your time!
